-- 2020-11-07 토요일
-- 9강 ~ 11강
ALTER TABLE MEMBER MODIFY ID NVARCHAR2(50); -- 컬럼 수정

ALTER TABLE MEMBER DROP COLUMN AGE;    -- 컬럼 삭제

ALTER TABLE MEMBER ADD EMAIL VARCHAR2(200); -- 컬럼 추가

CREATE TABLE NOTICE
(
     ID		NUMBER,
     TITLE 		NVARCHAR2(100),
     WRITER_ID	NVARCHAR2(50),
     CONTENT	CLOB,
     REGDATE  	TIMESTAMP,
     HIT		NUMBER,
     FILES		NVARCHAR2(1000)
);

CREATE TABLE "COMMENT"
(
     ID		NUMBER,
     CONTENT	NVARCHAR2(2000),
     REGDATE  	TIMESTAMP,
     WRITER_ID	NVARCHAR2(50),
     NOTICE_ID	NUMBER
);

CREATE TABLE ROLE
(
     ID		VARCHAR2(50),
     DISCRIPTION 	NVARCHAR2(500)
);

CREATE TABLE MEMBER_ROLE
(
     MEMBER_ID	NVARCHAR2(50),
     ROLE_ID		VARCHAR2(50)
);

INSERT INTO MEMBER(ID, PWD) VALUES('newlec', '111');
INSERT INTO MEMBER(ID, PWD) VALUES('dragon', '111');
SELECT * FROM MEMBER;
SELECT ID, NAME, PWD FROM MEMBER;
SELECT ID AS USER_ID, PWD FROM MEMBER;
SELECT ID USER_ID, PWD FROM MEMBER;
SELECT ID AS "USER ID", PWD FROM MEMBER;

COMMIT;